theme: jekyll-theme-hacker
title: Vartalap
description: Vartalap is an open source chatting application. It is design to provide the transparency in the personal messaging application with your data.
